#![allow(dead_code)]

#[path = "../contracts/src/c_consts.rs"]
mod c_consts;

use std::{env, fs, process};

fn as_nat(name: &str, value: i128) -> i128 {
    assert!(value >= 0, "{name} must be non-negative, got {value}");
    value
}

fn render() -> String {
    format!(
        "-- This file is generated by verification/generate_constants.rs.\n\
         -- Do not edit it directly.\n\n\
         import Mathlib\n\n\
         namespace CometCPow\n\n\
         def BONE : ℕ := {}\n\
         def STROOP : ℕ := {}\n\
         def MIN_WEIGHT : ℕ := {}\n\
         def MAX_CPOW_ITERS : ℕ := {}\n\
         def MAX_CPOW_EXP : ℕ := {}\n\n\
         end CometCPow\n",
        as_nat("BONE", c_consts::BONE),
        as_nat("STROOP", c_consts::STROOP),
        as_nat("MIN_WEIGHT", c_consts::MIN_WEIGHT),
        as_nat("MAX_CPOW_ITERS", c_consts::MAX_CPOW_ITERS),
        as_nat("MAX_CPOW_EXP", c_consts::MAX_CPOW_EXP),
    )
}

fn main() {
    let args: Vec<String> = env::args().skip(1).collect();
    match args.as_slice() {
        [] => print!("{}", render()),
        [flag, path] if flag == "--check" => {
            let expected = render();
            let actual = fs::read_to_string(path).unwrap_or_else(|error| {
                eprintln!("failed to read {path}: {error}");
                process::exit(1);
            });
            if actual != expected {
                eprintln!("{path} is stale; regenerate it with verification/generate_constants.rs");
                process::exit(1);
            }
        }
        _ => {
            eprintln!("usage: generate_constants [--check <generated-file>]");
            process::exit(2);
        }
    }
}
